# Generated by Django 5.0.6 on 2024-05-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ass1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(through='Ass1.StudentEnrolment', to='Ass1.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to='Ass1.lecturer'),
        ),
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ass1.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='Ass1.course'),
        ),
        migrations.AlterField(
            model_name='studentenrolment',
            name='gradeTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
